wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.7
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1690784330.58153
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      - 63
      3:
      - 2
      - 23
      4: 3.8.10
      5: 0.15.7
      8:
      - 1
      - 2
      - 5
