wandb_version: 1

framework:
  desc: null
  value: fastai
img_size:
  desc: null
  value:
  - 180
  - 320
batch_size:
  desc: null
  value: 8
augment:
  desc: null
  value: true
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.002
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.7
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1691389267.083944
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      - 63
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.15.7
      8:
      - 1
      - 2
      - 5
Learner:
  desc: null
  value:
    loss_func:
      axis: 1
      flatten: true
      floatify: false
      is_2d: true
      _name: FlattenedLoss of CrossEntropyLoss()
    opt_func: fastai.optimizer.Adam
    lr: 0.001
    splitter: fastai.vision.learner._resnet_split
    metrics:
    - <utils.MIOU object at 0x7f26be7b3b20>
    - <utils.BackgroundIOU object at 0x7f26be7b3c10>
    - <utils.RoadIOU object at 0x7f26be7b3b50>
    - <utils.TrafficLightIOU object at 0x7f26be7b3850>
    - <utils.TrafficSignIOU object at 0x7f26be7b3f40>
    - <utils.PersonIOU object at 0x7f26be7b3250>
    - <utils.VehicleIOU object at 0x7f26bbb01eb0>
    - <utils.BicycleIOU object at 0x7f26bbb01ee0>
    path: .
    model_dir: models
    wd: null
    wd_bn_bias: false
    train_bn: true
    moms:
    - 0.95
    - 0.85
    - 0.95
    default_cbs: true
    arch: torchvision.models.resnet.resnet18
    normalize: true
    n_out: 7
    pretrained: true
    _name: <fastai.learner.Learner object at 0x7f26f0212310>
TrainEvalCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
CastToTensor:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
ParamScheduler:
  desc: null
  value: true
SaveModelCallback:
  desc: null
  value:
    fname: model
    every_epoch: false
    at_end: false
    with_opt: false
WandbCallback:
  desc: null
  value:
    log: null
    log_preds: false
    log_preds_every_epoch: false
    log_model: true
    model_name: null
    log_dataset: false
    dataset_name: null
    valid_dl: null
    n_preds: 36
    seed: 12345
    reorder: true
n_inp:
  desc: null
  value: 1
input 1 dim 1:
  desc: null
  value: 8
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 180
input 1 dim 4:
  desc: null
  value: 320
batch size:
  desc: null
  value: 8
batch per epoch:
  desc: null
  value: 100
model parameters:
  desc: null
  value: 31113508
device:
  desc: null
  value: cuda
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 2
dataset.tfms:
  desc: null
  value: '[Pipeline: ColReader -- {''cols'': ''image_fname'', ''pref'': '''', ''suff'':
    '''', ''label_delim'': None} -> PILBase.create, Pipeline: ColReader -- {''cols'':
    ''label_fname'', ''pref'': '''', ''suff'': '''', ''label_delim'': None} -> PILBase.create]'
dls.after_item:
  desc: null
  value: 'Pipeline: AddMaskCodes -> Resize -- {''size'': (320, 180), ''method'': ''crop'',
    ''pad_mode'': ''reflection'', ''resamples'': (2, 0), ''p'': 1.0} -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
dls.after_batch:
  desc: null
  value: "Pipeline: IntToFloatTensor -- {'div': 255.0, 'div_mask': 1} -> Flip -- {'size':\
    \ None, 'mode': 'bilinear', 'pad_mode': 'reflection', 'mode_mask': 'nearest',\
    \ 'align_corners': True, 'p': 0.5} -> Brightness -- {'max_lighting': 0.2, 'p':\
    \ 1.0, 'draw': None, 'batch': False} -> Normalize -- {'mean': tensor([[[[0.4850]],\n\
    \n         [[0.4560]],\n\n         [[0.4060]]]], device='cuda:0'), 'std': tensor([[[[0.2290]],\n\
    \n         [[0.2240]],\n\n         [[0.2250]]]], device='cuda:0'), 'axes': (0,\
    \ 2, 3)}"
